GET localhost:8080/organizers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhIiwiaWF0IjoxNzE1MDI3MTM1LCJleHAiOjE3MTUwNjE2OTV9.wGQlWdyC5mmtjhEaUe-Bam1VzlDyfnyAQIBNbwPPkwk

###
GET http://localhost:8080/allEvents
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhIiwiaWF0IjoxNzE1MDI3MTM1LCJleHAiOjE3MTUwNjE2OTV9.wGQlWdyC5mmtjhEaUe-Bam1VzlDyfnyAQIBNbwPPkwk


### locations with organizer id =

GET localhost:8080/events?organizerId=101
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0b21hYm9nZGFuQGdtYWlsLmNvbSIsImlhdCI6MTcxMzk0NTUyNSwiZXhwIjoxNzEzOTgwMDg1fQ.st_pAuuVgCdAxi6BMwm9y20pNh236usNoTgHH6xESXE

### get event by id

GET localhost:8080/events/501
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhIiwiaWF0IjoxNzE1MDI3MTM1LCJleHAiOjE3MTUwNjE2OTV9.wGQlWdyC5mmtjhEaUe-Bam1VzlDyfnyAQIBNbwPPkwk

### get event info by id (tickets available)
GET localhost:8080/eventInfo?eventId=501
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhIiwiaWF0IjoxNzE1MDI3MTM1LCJleHAiOjE3MTUwNjE2OTV9.wGQlWdyC5mmtjhEaUe-Bam1VzlDyfnyAQIBNbwPPkwk

### get ticket by id
GET http://localhost:8080/info?id=801
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0b21hYm9nZGFuQGdtYWlsLmNvbSIsImlhdCI6MTcxMzk0NTUyNSwiZXhwIjoxNzEzOTgwMDg1fQ.st_pAuuVgCdAxi6BMwm9y20pNh236usNoTgHH6xESXE

### get multiple events with list o ids
GET http://localhost:8080/multipleEvents?ids=501&ids=502
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0b21hYm9nZGFuQGdtYWlsLmNvbSIsImlhdCI6MTcxMzk0NTUyNSwiZXhwIjoxNzEzOTgwMDg1fQ.st_pAuuVgCdAxi6BMwm9y20pNh236usNoTgHH6xESXE

### rename attendee on ticket
PUT http://localhost:8080/registration
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0b21hYm9nZGFuQGdtYWlsLmNvbSIsImlhdCI6MTcxMzkwMTQ1MywiZXhwIjoxNzEzOTM2MDEzfQ.2VE_llhqbFnsOU5M0-4PKhgbWrNHhxMzmAjvlCB0TDs
Content-Type: application/json

{"ticketCode": "c134520d-24e2-4d49-bcc4-4cf65cd7d40f", "eventId": 803, "id":4, "attendeeName": "Alex Mihai Pesu"}

### post registrations (only for users)
POST localhost:8080/registration
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0b21hYm9nZGFuQGdtYWlsLmNvbSIsImlhdCI6MTcxMzk0NTUyNSwiZXhwIjoxNzEzOTgwMDg1fQ.st_pAuuVgCdAxi6BMwm9y20pNh236usNoTgHH6xESXE
Content-Type: application/json

{"eventId": 801, "attendeeName": "Toma Bogdan Andrei"}

###
POST localhost:8080/registration
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1JHQU5JWkVSIiwic3ViIjoiYmJjY0NDQ2NjQ0FBQUFBQUFjYmEiLCJpYXQiOjE3MTM5MTMyODQsImV4cCI6MTcxMzk0Nzg0NH0.L5gW6jNgf2ee5n5RIQ5-sQW4Jk4bipN3tdl_1BqrbBE
Content-Type: application/json

{"eventId": 802, "attendeeName": "Orzata Gabriel"}

###
POST localhost:8080/registration
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiJiYmNjQUFBQUFBQWNiYSIsImlhdCI6MTcxMzkwOTQ1NiwiZXhwIjoxNzEzOTQ0MDE2fQ.qOtCDC-yk7e1HbBGGUxRMmd-i46Cxu6huWCIuEyimhw
Content-Type: application/json

{"eventId": 803, "attendeeName": "Alex Pesu"}

### register user
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "firstName": "gicu",
  "lastName": "grozav",
  "role": "ORGANIZER",
  "email": "gicugrozav@mail.com",
  "password": "bbb"
}

### login
POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
  "email": "plspls",
  "password": "plspls"
}

### post event (only organizers)
POST http://localhost:8080/postEvent
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwbHNwbHMiLCJpYXQiOjE3MTUzODMwNTQsImV4cCI6MTcxNTQxNzYxNH0.n9fshc_Y5YDgV6-gYJlzr5ecab3VVeaX_kzJdgsderk
Content-Type: application/json

{
  "name": "Spring Boot Workshop 1",
  "organizerId": 101,
  "locationId": 201,
  "startDate": "2024-04-15",
  "endDate": "2024-04-16",
  "description": "This is a test description"
}
### Error handling
###
GET localhost:8080/events/100
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0b21hYm9nZGFuQGdtYWlsLmNvbSIsImlhdCI6MTcxMzkwMTQ1MywiZXhwIjoxNzEzOTM2MDEzfQ.2VE_llhqbFnsOU5M0-4PKhgbWrNHhxMzmAjvlCB0TDs

###
###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "firstName": "bbcC",
  "lastName": "bbb",
  "role": "ORGANIZER",
  "email": "bbccCCCccCAAAAAAAcba",
  "password": "bbb"
}

###
POST http://localhost:8080/registration
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhIiwiaWF0IjoxNzE1MjgxNzU5LCJleHAiOjE3MTUzMTYzMTl9.efsmoZNTI_dbsdgrY8bLZcu3NCdSZmc6OMdMe1UsSaA
Content-Type: application/json

{
  "id": 0,
  "eventId": 503,
  "user": {
    "id": 54
  },
  "eventInfo": {
    "id": 801
  }
}

###
POST http://localhost:8080/registration
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhIiwiaWF0IjoxNzE1MzU3OTM0LCJleHAiOjE3MTUzOTI0OTR9.KnZ2HtA0fGoOr1HkdijKvVrHWfKciua9lLJpv6aeT1o
Content-Type: application/json

{
  "userId": 553,
  "eventInfoId": 801
}

###
PUT http://localhost:8080/registration/61/811
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhIiwiaWF0IjoxNzE1MzU3OTM0LCJleHAiOjE3MTUzOTI0OTR9.KnZ2HtA0fGoOr1HkdijKvVrHWfKciua9lLJpv6aeT1o
Content-Type: application/json

### get registration by ticketcode
GET http://localhost:8080/registration/1f887ddc-f0be-453f-acb9-eb81cd7370c4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhIiwiaWF0IjoxNzE1MzU3OTM0LCJleHAiOjE3MTUzOTI0OTR9.KnZ2HtA0fGoOr1HkdijKvVrHWfKciua9lLJpv6aeT1o

### get registration by event and user
GET http://localhost:8080/registration/check?userId=553&eventInfoId=801
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhIiwiaWF0IjoxNzE1MzU3OTM0LCJleHAiOjE3MTUzOTI0OTR9.KnZ2HtA0fGoOr1HkdijKvVrHWfKciua9lLJpv6aeT1o

### get registrations of a user
GET http://localhost:8080/registration/user/553
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhIiwiaWF0IjoxNzE1MzU3OTM0LCJleHAiOjE3MTUzOTI0OTR9.KnZ2HtA0fGoOr1HkdijKvVrHWfKciua9lLJpv6aeT1o

### delete registration
DELETE http://localhost:8080/registration/66
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhIiwiaWF0IjoxNzE1MzU3OTM0LCJleHAiOjE3MTUzOTI0OTR9.KnZ2HtA0fGoOr1HkdijKvVrHWfKciua9lLJpv6aeT1o

###
GET http://localhost:8080/users/email?email=a
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhIiwiaWF0IjoxNzE1MzU3OTM0LCJleHAiOjE3MTUzOTI0OTR9.KnZ2HtA0fGoOr1HkdijKvVrHWfKciua9lLJpv6aeT1o

###
GET http://localhost:8080/locations
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhIiwiaWF0IjoxNzE1MzU3OTM0LCJleHAiOjE3MTUzOTI0OTR9.KnZ2HtA0fGoOr1HkdijKvVrHWfKciua9lLJpv6aeT1o


###
DELETE http://localhost:8080/deleteEvent/16
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwbHNwbHMiLCJpYXQiOjE3MTUzODMwNTQsImV4cCI6MTcxNTQxNzYxNH0.n9fshc_Y5YDgV6-gYJlzr5ecab3VVeaX_kzJdgsderk

###
POST http://localhost:8080/feedback
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwbHNwbHMiLCJpYXQiOjE3MTUzODMwNTQsImV4cCI6MTcxNTQxNzYxNH0.n9fshc_Y5YDgV6-gYJlzr5ecab3VVeaX_kzJdgsderk
Content-Type: application/json

{
  "feedbackType": "aa",
  "satisfaction": "aaa",
  "newsletterSubscription": false,
  "comments": "aaa",
  "userId": 1
}